title: <p align="center"> Bhanu Dharmapuri </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/bhanu-dharmapuri-972065223/">LinkedIn</a> |
  <a href="https://github.com/bhanudharma">GitHub</a>
  
  <br>   
  I have 10+ years of experience in IT industry. 
  I have experience working in Python, Hive, GIT, GITHUB, MongoDB.
  <br>
  </p>

theme: jekyll-theme-minimal