title: Bhanu Dharmapuri
logo: /assets/img/logo.png
description: I have 10+ years of experience in IT industry. I have experience working in Python, Hive, GIT, GITHUB, MongoDB.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
